### PR TITLE
Support dev environment with docker-compose and docker

### PR DESCRIPTION
**Pull request by nllong**
* Adds new FMU-based tests that run with `pytest -m fmu`. These tests need to run in docker at the moment since it uses pyfmi that is compiled with Python2.
* Add back in the missing workflow.tar.gz file that is used with OSM files. Not sure how this was removed.
* New CI to run FMU tests
* mutlistage build on Dockerfile to support development environment in Docker. This allow you to develop locally and have the worker automatically restart when files are changed'
* Change name of `docker-compose-historian.yml` to `docker-compose.historian.yml`
* Move BCVTB setup dir to /home/alfalfa so it is not overwritten when creating the dev environment

To test:
* `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build`
* In a separate window run `docker exec alfalfa_worker_1 /bin/bash -c "cd /alfalfa && pytest -m fmu"`. Assuming you checked out your code into a directory named 'alfalfa'

Partially addresses #207

### CODE REVIEW

**Review by TShapinsky — COMMENTED** [review]
Did you mean to commit `workflow.tar.gz`?

**Comment by nllong** [comment]
> Did you mean to commit `workflow.tar.gz`?

I did. That file is required when running the OSM files. I’m not sure how it could work if not there and there has been a command in the dockerfile to extract it.

**Comment by TShapinsky** [comment]
> > Did you mean to commit `workflow.tar.gz`?
> 
> I did. That file is required when running the OSM files. I’m not sure how it could work if not there and there has been a command in the dockerfile to extract it.
> 
> See https://github.com/NREL/alfalfa/blob/develop/alfalfa_worker/Dockerfile#L85-L86

Ahh, I think my confusion stemmed from reading the additions to the `.gitignore` and not seeing the bang on the file name. 

Additionally, when I try to run the `docker exec ...` test I get an error saying no container names `/bin/bash`. Which container should that test be run on?

**Comment by nllong** [comment]
> > > Did you mean to commit `workflow.tar.gz`?
> > 
> > 
> > I did. That file is required when running the OSM files. I’m not sure how it could work if not there and there has been a command in the dockerfile to extract it.
> > See https://github.com/NREL/alfalfa/blob/develop/alfalfa_worker/Dockerfile#L85-L86
> 
> Ahh, I think my confusion stemmed from reading the additions to the `.gitignore` and not seeing the bang on the file name.
> 
> Additionally, when I try to run the `docker exec ...` test I get an error saying no container names `/bin/bash`. Which container should that test be run on?

doh, I forgot to add in the container to that command. It should be

`docker exec alfalfa_worker_1 /bin/bash -c "cd /alfalfa && pytest -m fmu"`

I updated above too!

**Review by TShapinsky — APPROVED** [review]

**Comment by anyaelena** [comment]
Late to review party but very happy to see this progress @nllong !

**Pull request merged**
