### PR TITLE
Update master

### PR DESCRIPTION
**Pull request by anyaelena**
@kbenne let me know of any gotchas you're aware of.  I assume we want this updated.  Or do we want to ditch master and start a `main` branch?

### CODE REVIEW

**Comment by nllong** [comment]
@anyaelena -- do you want to address the conflicts before I review?

**Comment by anyaelena** [comment]
@nllong i removed the review request (sorry for confusion).  For now, I mostly want a sanity check on whether there's a reason NOT to update master.

**Comment by nllong** [comment]
gotcha. I have no objections on merging to master.

**Comment by kbenne** [comment]
@anyaelena I have no concerns about this PR. I do think the project is settling down enough that we should begin thinking about some kind of release cadence. I support any type of branch structure that you choose if you want something other than master, develop, feature, setup then I don't have any complaints.

**Pull request merged**
