### PR TITLE
format steposm and fix Timestep error

### PR DESCRIPTION
**Pull request by corymosiman12**
In `in.idf`, all of the 'ZoneTimeStep' lines were catching on the `if 'Timestep,' in line`.  This replaced the time_step where we didn't want it (i.e. the line after `ZoneTimeStep` for the last `EnergyManagementSystem:OutputVariable` in the IDF file.  Did a full line check, along with asserting objects are found.
```
EnergyManagementSystem:OutputVariable,
  current_day,                            !- Name
  cur_day,                                !- EMS Variable Name
  Averaged,                               !- Type of Data in Variable
  ZoneTimeStep,                           !- Update Frequency
  ,                                       !- EMS Program or Subroutine Name
  ;                                       !- Units
```

### CODE REVIEW

**Comment by corymosiman12** [comment]
@kbenne and @YanfeiNREL can you guys merge this?

**Comment by corymosiman12** [comment]
@kbenne ...?  This will help others working with `develop` to not have issues when trying idf files that have a `ZoneTimeStep` field

**Comment by nllong** [comment]
@corymosiman12 is this branch/PR still valid? If not, then close and delete.

**Comment by corymosiman12** [comment]
The functionality has been duplicated in the OSMModelAdvancer class.  Whether or not this is best approach for manipulating IDF settings is still a valid question (@nllong or @kbenne thoughts?)

Since this was also merged into the `cbi` branch (which is where we initially noticed the issues), this will be closed.
 https://github.com/NREL/alfalfa/blob/b013253cf482bd0af0c0431d0cab2be305d7ccbc/alfalfa_worker/step_sim/osm_model_advancer.py#L219-L287

**Pull request closed without merging**
