### PR TITLE
Update to OpenStudio 3.1

### PR DESCRIPTION
**Pull request by kbenne**
This also means EnergyPlus 9.4

### CODE REVIEW

**Comment by kbenne** [comment]
Hey @anyaelena are you good with this becoming develop?

**Review by anyaelena — APPROVED** [review]

**Comment by anyaelena** [comment]
@kbenne works for me! Thanks again!

**Comment by kbenne** [comment]
@anyaelena guess I need to get tests passing first. I have a different branch where I fixed several things that I believed were independent of OS version, but that might have been a false assumption.

https://github.com/NREL/alfalfa/tree/fix-internal-clock

**Comment by anyaelena** [comment]
@kbenne should this branch be deleted since this update is now in emerson branch?

**Comment by kbenne** [comment]
yes

**Pull request closed without merging**
