### PR TITLE
Add in Log Stack (ELK) for docker-compose

### PR DESCRIPTION
**Pull request by tijcolem**
Adding in the ELK log stack for docker-compose. The file with the ELK service components is called: `docker-compose.elk.yml`

This optional file is appended to the docker-compose cli command at startup. e.g. 

`docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.elk.yml  up`

Kibana is the Web UI to view all the logs and resource metrics for the stack. It's accessible at `http://localhost:5601`

### CODE REVIEW

**Comment by anyaelena** [comment]
At `http://localhost:5601` i have `Kibana server is not ready yet`

**Comment by tijcolem** [comment]
Did elasticsearch container startup? Deploying ELK does require more cpu/mem. If you running docker on Windows or Mac you may need to bump up the docker VM's resources a bit.

**Comment by anyaelena** [comment]
I had two things going on. First, I had to remove the docker-compose.dev.yml because #288.  Then, I had to increase resource allocations for Docker locally.  Now Kibana is running.  

The CI errors I believe are coming from something unrelated to this PR that's gone wrong for web builds( @axelstudios ).

**Review by anyaelena — APPROVED** [review]
I've been using the logging stack.  This PR also includes fixes in web.

**Pull request merged**
