### PR TITLE
Cbi to replace master 

### PR DESCRIPTION
**Pull request by aviveiros11**
PR the bring master up to date with the latest cbi updates.

### CODE REVIEW

**Comment by corymosiman12** [comment]
My only comments:

- as we are not currently using kubernetes, does it make sense to somehow break out the kubernetes deployment stuff into a separate folder / directory...maybe it doesn't matter?

**Comment by aviveiros11** [comment]
> My only comments:
> 
> * as we are not currently using kubernetes, does it make sense to somehow break out the kubernetes deployment stuff into a separate folder / directory...maybe it doesn't matter?
> 
> @anyaelena is this something we want to leave in?

**Comment by aviveiros11** [comment]
@corymosiman12, @anyaelena  I could also maintain the k8's deployment files on a separate branch and remove them from this branch to serve as the new master.  That way we preserve that configuration and can merge in later if need be.

**Comment by corymosiman12** [comment]
That makes sense to me

**Comment by corymosiman12** [comment]
Cool - looks good

**Pull request merged**
