### PR TITLE
Python dependency management

### PR DESCRIPTION
**Pull request by TShapinsky**
Addresses #110 

When a OpenStudio run is created the job checks for any `requirements.txt` files. If any are found it creates a virtual environment in the run directory and installs packages. The E+ idf is then modified to point to that directory via its python path. This could and should be used by energy modelers to get their python dependencies into alfalfa. The main goal is to make it possible to add dependencies without having to create custom images and restarting the server.

The main downside (that I can see) from this change is that models which take advantage of this will have significantly larger than those without a virtual environment. This is because the entire environment is packaged with the run. One alternative would be to install packages worker wide, however, this would mean that packages would need to be installed on every worker and it would introduce the possibility of weird python dependency conflicts between models.

If this gets merged I will add wiki docs to the openstudio section.

### CODE REVIEW

**Comment by TShapinsky** [comment]
Previous commit tells the venv to use system site packages when possible and to symlink when it can instead of copying from the system python. Since the entire python stack is built before the image is created I think symlinks should continue to work between workers.

**Comment by anyaelena** [comment]
@TShapinsky With this change to venv/run, we should also remove the data-sci Python deps that are being installed on worker to support E+/Python.

**Review by nllong — APPROVED** [review]
this looks great. I second Anya's comment about removing dependencies on the worker that aren't needed by every simulation. I have some tweaks in my mongo schema branch to Dockerfile and poetry as well, but it shouldn't conflict...

**Comment by nllong** [comment]
> 

I think another downside is that each worker will have to undergo the `pip install` on `create_run`, meaning that it will take longer to provision new workers to scale out.

**Comment by TShapinsky** [comment]
> > 
> 
> I think another downside is that each worker will have to undergo the `pip install` on `create_run`, meaning that it will take longer to provision new workers to scale out.

Yeah, though this will only happen if the model is using python plugins with dependencies. Also, after the initial download of a package it is cached by the worker so subsequent installs are much faster. 

In my testing the biggest performance hit is actually the time it takes to tar the much larger run and upload it.

**Comment by TShapinsky** [comment]
@nllong I looked at the dependencies we are currently installing and I think most of them are used in the modelica side. So I don't think there's a lot we can remove at this time.

**Comment by nllong** [comment]
> @nllong I looked at the dependencies we are currently installing and I think most of them are used in the modelica side. So I don't think there's a lot we can remove at this time.

no surprised, to be honest. I think this is good to merge.

**Pull request merged**
